### PR TITLE
Enhancement of ships with the retrofit option

### PR DESCRIPTION
**Pull request by hjk22**
The `enhancement.py` module could not handle the enhancement of ships with the retrofit option because where the script expected to find the "enhance" tab, it found the "retrofit" one, so I added support for that case.

### CODE REVIEW

**Comment by Egoistically** [comment]
Wouldn't this be an easier solution? 
https://i.imgur.com/Nrk2z6M.png

**Comment by hjk22** [comment]
Sorry for the late reply. You're right, your solution is certainly easier to understand and more compliant with the rest of the code. If it works, I see no reason why choose mine over yours. Do you think you can commit your solution yourself?

**Comment by Egoistically** [comment]
Whatever you prefer, I tested my code with Sandy Kai and it worked fine.

**Comment by hjk22** [comment]
Then let's use your code. I'll wait to delete this branch, just in case.

**Comment by Egoistically** [comment]
I will test it out with another ship and push the changes later, thank you for reminding me of this and for your effort though.

**Pull request closed without merging**
