### PR TITLE
Fix 12-1 map

### PR DESCRIPTION
**Pull request by JustShinobi**
- asset fleet_2_up.png enabled for better recognition, now map 12-1  is fully functional.

### CODE REVIEW

**Comment by Egoistically** [comment]
Can you show me the results of this?

**Comment by JustShinobi** [comment]
> Can you show me the results of this?

I don't have any log now, but I did more than 10 runs without error, the big problem with this map is when the enemy appears where I marked it with red. it solved it in other ways but then I saw that there was this asset fleet_2_up.png in the folder, unused by the way, tested with him and voila, no further error occurred when enemies appeared at the top anymore.

**Comment by JustShinobi** [comment]
3 runs now, working perfectly.

**Pull request merged**
