### PR TITLE
Color screen, raw screencap and improved dorm refilling

### PR DESCRIPTION
**Pull request by asd111333**
1. add support for screencap raw mode
2. improve dorm refilling
3. extend Utils.find and Utils.find_and_touch with color screen
4. Utils.update_screen now stores a copy of color screen
5. add screen and color screen as class variable of Utils
6. add Utils.get_region_color_average

### CODE REVIEW

**Comment by hjk22** [comment]
Thank you! Now the refilling function is actually useful!
I still haven't tested your changes though: after I'm done with that, I will update you!

**Comment by hjk22** [comment]
I found out that `get_region_color_average` works only with numpy version >= 1.18.0, since in the previous versions `numpy.expand_dims`' axis parameter didn't accept tuples but only ints.
Anyway, after updating the library there weren't problems, so we'll just need to specify that in the requirements.

As for the supplies used to refill the bar, it would be nice if you could specify which ones can be used from the configuration file's settings. I don't know if you want to implement that too, but it would be great if you did.

**Comment by asd111333** [comment]
I am willing to do it, but I need sometime to understand how the configuration parser works.

**Comment by hjk22** [comment]
I read your changes and the option you provided in the configuration file was what I wanted, so good job! If I had to nitpick, I would say it would have been better using commas as separator for the values instead of a space, but that's my opinion.

I saw that you have also updated the dependencies in `requirements.txt`, and while there's no problem updating scipy, I'm not sure about opencv. I know that the function `findContours` has been slightly changed from v3, where it returned three values instead of two in v4.
Do you know if other functions have been changed (or at least the ones used in ALAuto)? Have you been running the bot with opencv4?

**Comment by asd111333** [comment]
I haven't tested it with the combat module. But it should work fine with the other modules.

**Comment by hjk22** [comment]
I know for sure that [find_siren_elites](https://github.com/Egoistically/ALAuto/blob/master/util/utils.py#L448) will need to be updated, but using `grab_contours` from imutils is enough to fix it. As for the rest, I'll run some tests later.

**Comment by hjk22** [comment]
I found no problems with updating the dependencies, so I think we can proceed with your changes.
Would you mind doing a rebase and resolve the conflicts?

**Comment by asd111333** [comment]
Updated. Please test it again. It also includes adding Screenshot mode in config.ini.

**Comment by hjk22** [comment]
Good work! Thank you very much!

**Pull request merged**
