### PR TITLE
Inform the user to lock their ships so retirement doesn't loop.

### PR DESCRIPTION
**Pull request by uuuulopta**
If you have ships that are either higher than lvl 1. or are in a formation the script gets stuck in a loop.
Now, there will be a message informing the user to lock their ships after which the script will close.
Added 2 assets, one is for the level thingy the other for the cancel button.

### CODE REVIEW

**Comment by hjk22** [comment]
Thank you for bringing attention to this scenario, but, to be honest, I don't really feel the need to add this since ships that are levelled or that are in some fleet formation should be locked and should never appear in the retirement selection, especially the latter. A player would need to go out of their way and unlock them in order for this scenario to happen, so I think it's quite unlikely.
About what you pushed, excluding a small typo (`cancle`, I think you meant `cancel`), I noticed you uploaded the wrong asset because you try to find `retirement/remove_from_formation` but you have uploaded the `cancel_button` one. Also I wanted to point out that you should make your commit messages more descriptive: nothing too fancy, but they should at least sum up what you did.
With that said, I still appreciate the fact that you took your time to try contributing to this project.

**Comment by uuuulopta** [comment]
Ah, sorry for uploading the wrong asset, I feel embarrassed - big mistake on my part.
I thought it would be a good idea since I have forgotten to lock one of the ships and some users might not have figured it out, and in general it's good to prevent the script from getting stuck in a loop. Regardless, thank you for your advice and I wish you luck with the project!

**Comment by uuuulopta** [comment]
remove_from_formation

Here is the proper asset if you wish to use it for any reason in the future.

**Comment by hjk22** [comment]
Thank you, and don't worry too much about your mistake, everybody can make them (just look at our commits' history).
In the future, if you have any other ideas feel free to propose them!

**Pull request closed without merging**
